<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<PackageId>illyW.Framework.Core</PackageId>
		<Version>1.3.1.0</Version>
		<Authors>William Paciaroni</Authors>
		<Company>illy-W</Company>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<AssemblyVersion>1.3.1.0</AssemblyVersion>
		<RepositoryUrl></RepositoryUrl>
		<FileVersion>1.3.1.0</FileVersion>
		<Description></Description>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RootNamespace>illyW.Framework.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<PackageOutputPath>..\nuGet</PackageOutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
	</ItemGroup>
	
</Project>
